//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EagleEye.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www
        ///_tcp
        ///_tls
        ///_udp
        ///_domainkey
        ///_pkixrep._tcp
        ///_aix._tcp
        ///_afpovertcp._tcp
        ///_autodiscover._tcp
        ///_caldav._tcp
        ///_certificates._tcp
        ///_cisco-phone-http
        ///_cisco-phone-tftp
        ///_cisco-uds._tcp
        ///_ciscowtp._tcp
        ///_cmp._tcp
        ///_collab-edge._tls
        ///_crl._tcp
        ///_crls._tcp
        ///_cuplogin._tcp
        ///_client._smtp
        ///_client._smtp._tcp
        ///_finger._tcp
        ///_sftp._tcp
        ///_ftp._tcp
        ///_gc._tcp
        ///_h323be._tcp
        ///_h323be._udp
        ///_h323cs._tcp
        ///_h323cs._udp
        ///_h323ls._tcp
        ///_h323ls._udp
        ///_h323rs._tcp
        ///_h323rs._udp
        ///_hkp._tcp
        ///_hkps._tcp
        ///_http._tcp
        ///_https._tcp
        ///_imap._tcp
        ///_imap.tcp
        ///_jabber-client [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultWordlist {
            get {
                return ResourceManager.GetString("defaultWordlist", resourceCulture);
            }
        }
    }
}
